title: "Hanieh Kashfi"
email: "kashfi.hanieh@gmail.com"
description: >-
  Academic webpage of Hanieh Kashfi
baseurl: ""
url: "https://your-username.github.io"

# Build settings
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: default
locale: "en-US"

# Navigation
header_pages:
  - publications.md
  - contact.md
